apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::313015929039:role/eksctl-eksctl-final-pipeline-node-NodeInstanceRole-1PLVM5VGEIZ73
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::313015929039:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-09T19:51:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1605"
  uid: 66a88876-3c2b-456e-a0c2-428ffbe380be
